version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t .

  build:
    commands:
      - echo "Zipping Lambda function and dependencies..."
      - zip -r lambda.zip .

  post_build:
    commands:
      - echo "Uploading lambda.zip to S3..."
      - aws s3 cp lambda.zip s3://class3-assign-lambda-deploymentfiles/lambda.zip

      - echo "Updating Lambda function..."
      - aws lambda update-function-code --function-name class3-assign-doordash-lambda --s3-bucket class3-assign-lambda-deploymentfiles --s3-key lambda.zip

      - echo "Waiting for Lambda code update to take effect..."
      - sleep 8

      - echo "Uploading trigger file to landing bucket..."
      - aws s3 cp doordash_input.json s3://class3-assigno-doordash-landing-zn/doordash_input.json
